# Docker Compose File for Application Container with Docker bindings
version: '3.8'

services:
  dev:
    image: ghcr.io/octodemo/development-containers/javascript:base-202401-r1
    command: sleep infinity
    
    working_dir: /workspaces/pure-octocat-supply-copilot-demo

    ports:
      - "3000:3000"
      - "5137:5137"

    volumes:
      # Mount the entire workspace
      - ..:/workspaces/pure-octocat-supply-copilot-demo:cached
      # Mount Docker socket for Docker-in-Docker capabilities
      - /var/run/docker.sock:/var/run/docker.sock
      
    # Keep container running
    tty: true
