name: Trivy AWS Compliance Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  trivy-compliance-cli:
    name: Trivy compliance scan from CLI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          version: v0.65.0
          cache: true

      - name: Run Trivy compliance scan
        run: |
          trivy aws \
            --report all \
            --format sarif \
            --output trivy-aws-compliance-results.sarif \
    
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-aws-compliance-results.sarif
          category: trivy-aws-compliance
