name: Trivy Config CLI Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  trivy-config-cli:
    name: Trivy config scan from CLI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          version: v0.65.0
          cache: true

      - name: Run Trivy config scan
        run: |
          trivy fs \
            --scanners misconfig \
            --config-check ./trivy/policies/no_policy_wildcards.rego \
            --namespaces custom \
            --format sarif \
            --output trivy-results.sarif \
            ./trivy/policies
    
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-config
      
      - name: Print SARIF result count
        if: always()
        run: |
          echo "SARIF results count: $(jq -r '[.runs[].results | length] | add // 0' trivy.sarif)"

      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy.sarif
          retention-days: 14
        