name: Trivy Config Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy:
    name: Trivy scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scanners: 'misconfig'
          scan-ref: '.'
          trivy-config: 'trivy/policies/trivy.yaml'
          format: 'sarif'
          output: 'trivy.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy.sarif'
          category: 'trivy-config'

      - name: Print SARIF result count
        if: always()
        run: |
          echo "SARIF results count: $(jq -r '[.runs[].results | length] | add // 0' trivy.sarif)"

      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy.sarif
          retention-days: 14
